### ISSUE TITLE
Programas para crear reportes

### ISSUE THREAD

**Issue by Ezmerallda7** [PFLC/db509#1]
Una de las partes a veces menos preciada, dentro de un software son los reportes que de este podemos extraer. Los reportes son documento (que puede ser impreso, digital, audiovisual, etc.) que pretende transmitir información clara y entendible acerca del estado, las características y/o circunstancias de un suceso o asunto.
 
La manera más fácil de observar el estado actual de un negocio a través de su software son las dashboard o los reportes que podemos extraer de ellos. 
 
Jasper es una poderosa herramienta open source totalmente escrita en java y se utiliza para la creación de informes, utiliza diversas clases de data sources, también permite incluir reportes dentro de otros, y exportarlos en los formatos más comunes como son XLS, PDF, RTF, CSV, XML, TXT  y HTML.
 
Existen dos herramientas totalmente visuales que nos facilita la creación de nuestros reportes Jaspersoft Studio y el iReport Designer (basado en netbeans).
FastReport.Net es una herramienta de generación de informes con muchísimas características para diseñadores de software .Net, que permiten al usuario a crear informes .Net independientes de la aplicación. La herramienta ha sido ampliamente reconocida gracias a su flexibilidad, su eficiencia y su rápida modificación a la hora de trabajar con ella. 
ShortcutsMan permite crear reportes del análisis de forma detallada en archivos de hipertexto o texto plano, lo que facilitará el estudio de los errores por parte de los usuarios. Por supuesto es un programa completamente libre de licencia freeware.
NetworkTrafficView ofrece la posibilidad de crear reportes de análisis y de ejecución, de manera que puede utilizarse como herramienta principal durante el proceso de mantenimiento de red, ya que podemos acceder rápidamente a cualquier información de tráfico de la red. Por supuesto cuenta con un sistema de interacción bastante simple y minimalista, que permite  visualizar con comodidad la información del proceso de monitorización, sin mermar el buen desempeño del equipo.
WinUpdatesList puede crear reportes en diferentes tipos de documentos de texto plano o de hipertexto, de manera que tengamos la posibilidad de realizar reportes de ejecución imprimibles. Por demás está decir que cuenta con un área de interacción bastante simple, que nos permitirá interactuar rápida y efectivamente con el programa.
HttpWatch es un poderoso Sniffer que se instala como un complemento de los navegadores web IE o Firefox y es utilizado para guardar todas las peticiones que se hacen a los servidores desde nuestros navegadores web utilizando el protocolo http. Por demás está decir que este programa cuenta con la opción de realizar una copia de los registros de dichas peticiones, de esta manera podemos consultarlos cuando deseemos o crear reportes completos en tiempo real de todas las peticiones hechas al sitio web.
SIW Home Edition realiza un análisis detallado y minucioso de cada uno de los elementos del sistema ya sea de hardware o de software y los despliega por pantalla, de manera sencilla de entender, clasificado por elementos. Todo este trabajo se hace directamente sobre un apartado visual bastante ligero e intuitivo y por si fuera poco permite crear reportes de estado que podemos exportar a formatos de texto o imprimirlos directamente desde el área de trabajo.
 
Entre otros.

**Comment by renesolis** [comment]
@Ezmerallda7 gracias por presentar
el trabajo a tiempo solo 2 lo entregaron
1 punto extra.
