### ISSUE TITLE
Reporteadores

### ISSUE THREAD

**Issue by ReneRayle22** [PFLC/db509#18]
Reportes Gráficos

Principalmente, los reportes gráficos de HMS se centran en brindar información rápida y visual al usuario. Debido a que se usan graficadores que funcionan en ambientes web, el usuario puede visualizar la información en gráficas lineares, de barra, de pie, etc.

La mayoría de los clientes de HMS utilizan los reporte gráficos para ver información a través del tiempo, como por ejemplo: Ventas / Compras / Utilidades mes a mes, comparativo de proyectos, porcentajes de participación de algún proyecto.

Adicionalmente, estos reportes pueden contar con la opción de DRILL DOWN, explicada en la pestaña que lleva su nombre, lo cual ayuda al usuario a navegar "hacia adentro" del reporte e ir filtrando información hasta llegar a un dato específico.

Reportes Tabulares

A diferencia de los reportes gráficos, los reportes tabulares que genera HMS son aquellos donde no se presentan gráficas, generalmente se presentan datos en forma líneal y sirven igualmente para comparar la información a través del tiempo o un condensado de información.

Los clientes de HMS piden ver este tipo de reportes en inventarios, ventas mes a mes, compras mes a mes.

Al igual, estos reportes también tiene la opción de DRILL DOWN, ya que se le pueden colocar ligas a cierto dato para poder ver o filtrar más información.

Reportes con Drill Down

Este reporte básicamente va navegando y filtrando a través de la información. Si el sistema está diseñado de tal manera que se pueden categorizar los productos o servicios, se puede partir de la categoría más amplia e ir navegando hacia "adentro" del reporte para ir desglosando la información.

Los clientes de HMS que piden este tipo de reportes es para ir analizando su información e ir buscando las razones de cada categoría, ya que el reporte les permite ir filtrando la información que ellos van solicitando.

Los ejemplos más claros en este tipo de reportes que pide el cliente son los de facturación por ubicación:

Nivel 1: Facturación por país.
Nivel 2: Desgloce por estado.
Nivel 3: Desgloce por ciudad.

Listados

Este tipo de reportes son los más sencillos que hace HMS, son listados o catálogos.

Es un despligue de información sobre productos, clientes, proveedores, usuarios o cualquier elemento que se encuentre en el sistema. Por default, los sistemas de HMS todos sus catálogos son listados que pueden ser consultados por los usuarios.

Fuente:
http://www.hms.mx/index.php?varPageName=SSD/index.php

**Comment by renesolis** [comment]
@ReneRayle22 pero cual libreria usaria para que su NetBeans genere reportes? calificación 9.
