### ISSUE TITLE
Reporteador

### ISSUE THREAD

**Issue by ismaelt** [PFLC/db509#19]
Un reporte es un Documento, generado por el Sistema, que nos presenta de manera Estructurada y/o Resumida, datos relevantes guardados o generados por la misma aplicación de tal manera que se vuelvan útiles para los fines que la Escuela o al Programa Escuelas de Calidad convengan.

Los reportes generalmente agrupan los datos de acuerdo a un interés específico; por ejemplo el reporte "Cheques emitidos por la Escuela", presenta una lista de todos los documentos que la Escuela ha dispuesto para pagar a proveedores o prEstadores de servicios, ordenados mediante números y fechas.

Los informes sirven para resumir y presentar los datos de las tablas. Normalmente, un informe responde a una pregunta específica, como "¿Cuánto dinero se ha facturado por cliente este año?" o "¿En qué ciudades están nuestros clientes?" Cada informe se puede diseñar para presentar la información de la mejor manera posible.
Un informe se puede ejecutar en cualquier momento y siempre reflejará los datos actualizados de la base de datos. Los informes suelen tener un formato que permita imprimirlos, pero también se pueden consultar en la pantalla, exportar a otro programa o enviar por correo electrónico.

*REPORTES 

Un reporte o Informe, como últimamente se le conoce es: Los informes son una manera excelente de organizar y presentar los datos de una base de datos. Los informes permiten aplicar formato a los datos dando lugar a un diseño atractivo e informativo en la pantalla o en las copias impresas.
1. Los informes pueden darles mayor utilidad a los datos.
2. Los informes pueden tener diferentes niveles de complejidad, desde una simple lista (como un informe sobre el estado de un proyecto o un informe semanal de ventas) hasta un catálogo detallado de productos.

LOS INFORMES TAMBIÉN PERMITEN:

1. Preparar facturas. 
2. Crear etiquetas postales. 
3. Crear un directorio, como una lista alfabética de empleados con su información de contacto. 
4. Permiten presentar un resumen de los datos, como las ventas agrupadas por región.
5. Los informes pueden resumir y agrupar los datos para proporcionar una introducción

Fuentes
http://manuelcruzhidalgo19.blogspot.mx/2013/02/informes-y-reportes_8863.html
http://optimusalca.blogspot.mx/2012/02/informes-y-reportes.html
http://optimusalca.blogspot.mx/2012_02_01_archive.html

**Comment by renesolis** [comment]
@ismaelt pero cual programa/libreria usará para dar solución a los reportes en su CRUD ?
califación 9
