### ISSUE TITLE
Programas para la creación de Reportes

### ISSUE THREAD

**Issue by enriqueperez509** [PFLC/db509#2]
En el ámbito de la informática, los reportes son informes que organizan y exhiben la información contenida en una base de datos. Su función es aplicar un formato determinado a los datos para mostrarlos por medio de un diseño atractivo y que sea fácil de interpretar por los usuarios.
Según el programa informático y la base de datos en cuestión, los reportes permiten la creación de etiquetas y la elaboración de facturas, entre otras tareas.
De la misma forma, gracias a los reportes cualquier persona puede proceder a realizar un resumen de datos o a clasificar estos en grupos determinados. Por todo ello, se entiende que estos documentos sean tan importantes en cualquier empresa ya que gracias a ellos cuenta con sus propias bases de datos (de trabajadores, de clientes, de proveedores…), realiza recopilaciones de las ventas acometidas en un periodo determinado.

Frecuente deseamos ver reportes sobre los datos que se generan en el sistema y, en ocasiones, se encuentran almacenados en nuestra base de datos.
Para ello existen opciones para la creación de estos reportes, como: 
- JasperReports: un programa OpenSource que nos permite generar reportes en formatos PDF, XML, HTML, CSV, XLS, RTF, y TXT con solo unas cuantas líneas de código y guardar este reporte en un archivo o mostrarlo directamente con un visor especial. 
- Otro programa para realizar reportes en Java, es la herramienta iReport que es un constructor / diseñador de informes visual, poderoso, intuitivo y fácil de usar para Java. Este instrumento permite que los usuarios corrijan visualmente informes complejos con cartas, imágenes, subinformes, etc.
- FastReport es una aplicación que permite añadir a los programas la posibilidad de generar reportes de manera rápida y eficiente.
- Report Manager:
Esta extraordinaria herramienta funciona para generar reportes completos de cualquier aplicación con la que estemos trabajando o sobre los datos o información con la cual dichas aplicaciones estén trabajando. Sólo está disponible para Linux.
- Agata Report es un complemento perfecto para crear todo tipo de reportes en cualquier  gestor de base de datos, permitiendo personalizar la detalle cada uno de los elementos de la base de datos para crear informes detallados de cualquier query que realicemos.
Agata Report cuenta con la versatilidad de poder trabajar con distintos tipos de gestores de base de datos. ofrece la posibilidad de crear informes en distintos formatos de texto como HTML, PDF, XML y PS. Disponible disponible para Linux

Por último encontré el programa Eclipse SDK ,que está compuesto por varias herramientas, a partir de las cuales el programador puede iniciar sus proyectos: utilidades de edición de texto, analizadores de código, interpretadores y más.

--------- Pérez Amador Enrique.    Grupo: 509------------

**Comment by renesolis** [comment]
@enriqueperez509  gracias tiene +1 punto extra
