### ISSUE TITLE
Reporteadores de Java

### ISSUE THREAD

**Issue by JoakinoHG** [PFLC/db509#20]
Un reporte permite presentar la información de una base de datos de forma organizada y estética en una hoja impresa, esta información es extraída o calculada a partir de los datos almacenados en la tabla.
Un reporte es un informe o una noticia. Este tipo de documento (que puede ser impreso, digital, audiovisual, etc.) pretende transmitir una información, aunque puede tener diversos objetivos. Existen reportes divulgativos, persuasivos y de otros tipos.

Un reporteador de base de datos en su caso seria el jasper report que te permite mostrar en forma de reporte
ya manipulados los datos que contenga tu base de datos
JasperReports es una herramientade creación de informes Java libre que tiene la habilidad de entregar contenido enriquecido al monitor, a la impresora o a ficheros PDF, HTML, XLS, CSV y XML.
Está escrito completamente en Java ypuede ser usado en gran variedad de aplicaciones de Java, incluyendo J2EE o aplicaciones web, para generar contenido dinámico.
El Diseñador de Reportes permite crear proyectos, conexiones a bases de datos, definir grupos de usuarios y usuarios y asegurar el sistema de reportes. Permite la creación de reportes, hojas de datos, gráficas y tablas dinámicas. Puede distribuir sus reportes a través de archivos físicos de reportes los cuales pueden ser abiertos por los usuarios finales con el Visor de Reportes Gratuito o a través del Servicio Web de Reportes donde los usuarios pueden abrir cualquier reporte con un navegador de Internet.
Su propósito principal es ayudar a crear documentos de tipo páginas,preparados para imprimir en una forma simple y flexible.
JasperReports se usa comúnmente con iReport, un front-end gráfico de código abierto para la edición de informes.
JasperReports es una librería de creación de informes que tiene la habilidad de entregar contenido enriquecido al monitor, a la impresora o a ficheros PDF, HTML, XLS, CSV y XML.

Está escrito completamente en Java y puede ser usado en gran variedad de aplicaciones de Java, incluyendo J2EE o aplicaciones web, para generar contenido dinámico. Se ha desarrollado un subproyecto que es un servidor integrado para informes: JasperReports Server.

Su propósito principal es ayudar a crear documentos de tipo páginas, preparados para imprimir en una forma simple y flexible.

JasperReports se usa comúnmente con iReport, un front-end gráfico de código abierto para la edición de informes, si bien a partir de la versión 5.5.0 iReport ha sido sustituido por Jaspersoft Studio, un front-end gráfico de código abierto basado en Eclipse.

![image](https://cloud.githubusercontent.com/assets/14998916/10900823/7cfa1b2a-8199-11e5-87f6-8609c1ea844f.png)

Joaquin Alberto Montaño Green----- Grupo 509

**Comment by renesolis** [comment]
@JoakinoHG que bien que localizo la solución para su NetBeans con 10.
