### ISSUE TITLE
Reporteador de Java

### ISSUE THREAD

**Issue by gollo24** [PFLC/db509#21]
¿Que es un reporte? 
Empresarialmente hablando es un informe que tiene como fin llevar a las manos de quien lo consulte informacion clave hacerca de: Ventas, Variaciones del mercado, costos y todos aquellos datos impresindibles para la toma de deciciones generenciales en las empresas.

 En este primer post veremos cómo crear reportes haciendo uso de una conexión a la base de datos directamente desde nuestro reporte.

Lo primero que haremos es crear una base de datos con tablas y datos de pruebas para poder tener algo interesante que ver en nuestros reportes. En este caso usaré MySQL versión 5.1, el cual pueden descargar desde su página oficial. Usando el conector para Java versión 5.1.13 que pueden descargar desde la página de MySQL. Pero cualquier base de datos que les guste funcionará para nuestros ejemplos.

La base de datos que usaré se llama "pruebaReportes" y contiene la tabla "participantes"

**Comment by renesolis** [comment]
@gollo24 buena propuesta esperamos este reporte con ansiedad, y gracias por superar la practica. 10 de calif. este trabajo.
