### ISSUE TITLE
Reporteador

### ISSUE THREAD

**Issue by jerryramirez** [PFLC/db509#23]
Un reporte es un informe o una noticia. Este tipo de documento  (que puede ser impreso, digital, audiovisual, etc.) pretende transmitir una información, aunque puede tener diversos objetivos. Existen reportes divulgativos, persuasivos y de otros tipos.

 
Reporte
El reporte puede ser la conclusión de una investigación previa o adoptar una estructura de problema-solución en base a una serie de preguntas. En el caso de los informes impresos, el texto suele ir acompañado por gráficos, diagramas, tablas de contenido y notas al pie de página.

 
En el ámbito de la informática, los reportes son informes que organizan y exhiben la información contenida en una base de datos. Su función es aplicar un formato determinado a los datos para mostrarlos por medio de un diseño atractivo y que sea fácil de interpretar por los usuarios.
El reporte, de esta forma, confiere una mayor utilidad a los datos. No es lo mismo trabajar con una planilla de cálculos con 10.000 campos que con un dibujo en forma de torta que presenta dichos campos de manera gráfica. Los reportes tienen diversos niveles de complejidad, desde una lista o enumeración hasta gráficos mucho más desarrollados.
Según el programa informático y la base de datos en cuestión, los reportes permiten la creación de etiquetas y la elaboración de facturas, entre otras tareas.
De la misma forma, gracias a los reportes cualquier persona puede proceder a realizar un resumen de datos o a clasificar estos en grupos determinados. Por todo ello, se entiende que estos documentos sean tan importantes en cualquier empresa ya que gracias a ellos cuenta con sus propias bases de datos (de trabajadores, de clientes, de proveedores…), realiza recopilaciones de las ventas acometidas en un periodo determinado…
Así, teniendo en cuenta los datos que abordan y la extensión que tienen, estos reportes se pueden luego clasificar en diversos niveles en cuanto a su complejidad dando lugar a catálogos, a listas, a resúmenes…
Para los medios de comunicación, un reporte es un contenido informativo. Puede tratarse de un programa (o de un segmento) televisivo o radial, una nota publicada en un periódico o una revista o de un documento digital. Por ejemplo: “Ahora vamos a ver el reporte sobre el estado del tránsito en la ciudad de Buenos Aires”, “Juan López nos presentará un reporte sobre la actuación de los tenistas chilenos en Roland Garros”.

**Comment by renesolis** [comment]
@jerryramirez  lo lamento esta medio raro su redacción parece copy-paste de http://definicion.de/reporte/ le pondremos un 5.4.
