### ISSUE TITLE
Github- Reporteadores

### ISSUE THREAD

**Issue by elisgarcia97** [PFLC/db509#24]
Para ello existe una opción para la creación de estos reportes: JasperReports. JasperReports es un API OpenSource que nos permite generar reportes en formatos PDF, XML, HTML, CSV, XLS, RTF, y TXT con solo unas cuantas líneas de código y guardar este reporte en un archivo, enviarlo por un OutputStream, o mostrarlo directamente con un visor especial (si usamos una aplicación swing).

Las dependencias transitivas son las librerias programadas en Java que se usaron para el desarrollo de JasperReports pero que son independientes a esta y no estan incluidas o empaquetadas en el jar como tal, si no que se deben incluir aparte, vamos a agregar las necesarias para ejecutar el proyecto.

Voy a crear una clase abstracta para programar las funcionalidades requeridas, la de crear el reporte, la de mostrar el visor con el reporte y la de exportar a pdf.

Los objetos que vamos a utilizar son tres: una llamado report, que va a ser el reporte como tal del sistema de archivos, otro llamado reportFilled, que es el reporte pero ya lleno con la información que trae el query interno. Y el otro llamado viewer que es el visor donde se va a mostrar el reporte.

Las siguientes son las importaciones de las clases e interfaces que necesitamos de los paquetes principales que son engine, engine.util y view.

Para cargar el reporte del sistema de archivos tener en cuenta que el método loadObjectFromFile retorna un tipo Object y no un tipo JasperReport, entonces debemos hacer un casting para una correcta asignación.

La ruta donde queremos guardar el archivo PDF debe tener doble backslash “\\” y además finalizar con el nombre del archivo con extensión .pdf

Llamamos al método para exportar a PDF desde el evento del botón
 Ejecutamos la aplicación

**Comment by renesolis** [comment]
@elisgarcia97 gracias por dar lectura a sitios relevantes para esta tarea. 10 esta participación.
