### ISSUE TITLE
Reporteadores JAVA

### ISSUE THREAD

**Issue by tellezortega** [PFLC/db509#3]
# Reporteadores JAVA
Frecuente, o mejor dicho siempre, los clientes desean ver reportes sobre los datos que se generan en el sistema y, en ocasiones, se encuentran almacenados en nuestra base de datos.
Un reporte es un informe o una noticia. Este tipo de documento (que puede ser impreso, digital, audiovisual, etc.) pretende transmitir unainformación, aunque puede tener diversos objetivos. Existen reportes divulgativos, persuasivos y de otros tipos.

Si han tenido que hacer reportes de 7 o más columnas sabrán que esto no es tan sencillo como muchos de nosotros podríamos pensar. Muchos desarrolladores me han comentado que es lo más fácil que hay ya que, a lo más, nos tardaremos media hora en "crear el query" para obtener los datos que necesitamos...

Si bien esto podría ser cierto en la mayoría de los casos, lo que no siempre es fácil es mapear estos datos a los objetos que vamos a usar y aún menos el formaterarlos de manera que nuestro reporte sea fácil de entender y le proporcione al cliente la suficiente información como para que este le sea de utilidad.
El reporte puede ser la conclusión de una investigación previa o adoptar una estructura de problema-solución en base a una serie de preguntas. En el caso de los informes impresos, eltexto suele ir acompañado por gráficos, diagramas, tablas de contenido y notas al pie de página.

En el ámbito de la informática, los reportes son informes que organizan y exhiben la información contenida en una base de datos. Su función es aplicar un formato determinado a los datos para mostrarlos por medio de un diseño atractivo y que sea fácil de interpretar por los usuarios.

El reporte, de esta forma, confiere una mayor utilidad a los datos. No es lo mismo trabajar con una planilla de cálculos con 10.000 campos que con un dibujo en forma de torta que presenta dichos campos de manera gráfica. Los reportes tienen diversos niveles de complejidad, desde una lista o enumeración hasta gráficos mucho más desarrollados.

Según el programa informático y la base de datos en cuestión, los reportes permiten la creación de etiquetas y la elaboración de facturas, entre otras tareas.

http://chio-basededatos.blogspot.mx/2012/02/informes-y-reportes.html
https://ingeniods.wordpress.com/2013/05/21/jasper-report-virtualizacion-y-generacion-de-reportes/
http://www.javatutoriales.com/2009/01/creacion-de-reportes-con-multiples.html

**Comment by renesolis** [comment]
Gracias @tellezortega  10 !
