### ISSUE TITLE
Reportes con JasperReports

### ISSUE THREAD

**Issue by FishNoodles** [PFLC/db509#33]
- En opinion/critica general del video puedo decir que es un poco obsoleto ya que la calidad y edicion de este es mala, haciendo que sea un poco monotono el video en si :unamused: Aunque si explica todos los pasos que realiza se apreciaria mas el esfuerzo por hacer este video si se tuviera un mejor microfono que no pareciera de audifonos/headset del 10 dlls :joy: 

- En referencia a lo que es Netbeans: Una vez que se anaden los plugins a netbeans es relativamente facil la utilizacion de esta herramienta aunque como todo en el area de la programacion toma tiempo. Configurandose correctamente podemos utilizar este reporteador para presentar dinamicamente la informacion de una base de datos en tipos de archivos como tan variados y conocidos como son el pdf.

- Hecho por: Michelle Pimentel Aramburo :panda_face:

**Comment by renesolis** [comment]
@FishNoodles Michelle Pimentel, gracias por la critica del video y atinadamente opinión.
