### ISSUE TITLE
Tarea2 Reportes Netbeans

### ISSUE THREAD

**Issue by ismaelt** [PFLC/db509#51]
en el vídeo te enseñan como crear un reporteador en java  netbeans con una librería llamada JasperReports, es necesario ya tener el proyecto iniciado y si quieres, es recomendado, crear una plantilla de reportes https://youtu.be/PBK8wiZ80wM para ahorrarte tiempo o descargar una,

https://youtu.be/P7sNWBOu6gg

el vídeo te dice todo lo que necesitas saber para crear un reporteador, http://www.mediafire.com/download/x7sx467uvxr3n6x/Librerias+y+dependencias.zip 
este es el link para descargar las librerías necesarias.

**Comment by renesolis** [comment]
Correcto @ismaelt  las librerías son de comunidad libre de cobro, claro si uno quiere reportes con Flash dinámicos ya uno buscaría soluciones con esa compañía para adquirir la versión Comercial ya es para empresas que hagan los pagos del reporteador.
