### ISSUE TITLE
#GitTarea2 Reportes JasperReport

### ISSUE THREAD

**Issue by malphitesn** [PFLC/db509#52]
https://www.youtube.com/watch?v=Bn4tiquJsSs
Bueno el reporteador JasperReport es Sencillo el crear y generar un reporte únicamente con la base de una tabla ya creada y en funcionamiento. Creamos el reporte > Report wizard> connection data source> Query (SQL) > elegimos campos que aparecerán en el reporte > Nos dará un mensaje "Congratulations" , nuestro reporte se habrá generado.
En este vídeo también nos muestra como crear un botón para que este mismo cree el reporte, y el jframe en el que se llamara al reporte.
Con este vídeo me queda mas en claro la utilidad de un reporte, y no solo ese uso que se le da si no el de una presentación.

**Comment by renesolis** [comment]
Gracias @malphitesn por esta tarea tiene 10.
