### ISSUE TITLE
GitTarea#1: Reportes en Netbeans con iReport

### ISSUE THREAD

**Issue by alex1298** [PFLC/db509#53]
En este video nos muestra esencialmente como se usa iReport y cual es su finalidad principal, nos enseña tambien lo basico de como conectarnos a una libreria y servidor. En iReport  podemos elaborar nuestro reporte sin salir del IDE, existe un plugin (archivo .nbm) para NetBeans que muestra el iReport dentro del mismo IDE.
En mi opinion este programa  permite realizar nuevos  registros es muy facil de usar, en mi opinión es muy importante saber usar estos tipos de programas por que  los puedes aplicar a diversos ámbitos de trabajo que son muy importantes para poder estar preparado al realizarlo.

**Comment by renesolis** [comment]
@alex1298 y @ReneRayle22  es la misma persona aparece misma redacción?
