### ISSUE TITLE
#GitTarea2 Realizacion de Reportes JasperReport

### ISSUE THREAD

**Issue by alex1298** [PFLC/db509#54]
En este video no enseña a aprender a usar JaserReport detalladamente, este es facil de  crear y generar un reporte únicamente con la base de una tabla ya hecha y en funcionamiento. En este video nos muestra como agregar las librerías necesarias para un uso básico y tambien nos explica las clases e interfaces principales de la librería de JasperReports y las funcionalidades que nos ofrecen y la localizaciona de los paquetes.
Con este video me quedo mas claro que es un JaserReport y cual es su funcion en especial, fue un video muy entretenido y facil de entender y seguir.

**Comment by renesolis** [comment]
@ReneRayle22  y @alex1298  son la misma redacción ??? aparece copy-paste
