### ISSUE TITLE
Como generar reportes en Netbeans con JasperReports

### ISSUE THREAD

**Issue by ReneRayle22** [PFLC/db509#55]
Este video nos enseña una manera muy sencilla y entendible para todos con conocimientos basicos de Netbeans como crear un reporte con iReport, descargando y poniendo los pugglins que el tutorial nos dice, tambien como conectarse a un servidor y crear librerias. Al seguir todos estos pasos crearas unn programa interactivo con el cual te dara entrada a registros y poder modificarlos; esto se puede usar en cualquier ambito, ya sea empresas, instituciones, trabajos, escuelas , etc...

 https://www.youtube.com/watch?v=_gCVASz4-44&feature=youtu.be

**Comment by renesolis** [comment]
@ReneRayle22 gracias por la aportación y el breve resumen de esta excelente libreria de comunidad para este fin. Suerte  en practica4CRUD.
